import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import cron from "node-cron";
import admin from "firebase-admin";
import axios from "axios";
import dotenv from "dotenv";
import { GoogleGenerativeAI } from "@google/generative-ai";

import fs from "fs";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load Firebase Config
const firebaseConfig = JSON.parse(fs.readFileSync(path.join(__dirname, "firebase-applet-config.json"), "utf8"));

// Initialize Firebase Admin
if (!admin.apps.length) {
  admin.initializeApp({
    projectId: firebaseConfig.projectId,
  });
}
const db = admin.firestore(firebaseConfig.firestoreDatabaseId);

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

// Automation Task
async function runAutomationPipeline() {
  const configRef = db.collection("settings").doc("config");
  const settingsDoc = await configRef.get();
  const settings = settingsDoc.data();
  
  if (!settings?.autoMode) {
    console.log("Auto-mode is OFF. Skipping pipeline.");
    return;
  }

  console.log("Starting Automation Pipeline...");

  try {
    // 1. Fetch Trends (using Gemini with Search or predefined logic)
    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
    const prompt = "Identify the top 5 most viral and trending topics in India right now in Tech, Business, and Health. Provide a JSON list of objects with 'title' and 'category'. Only return raw JSON.";
    
    // For environment without search enabled, we'll simulate or use a fallback
    // In a real scenario, we'd use grounding or a dedicated news API
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    let trends = [];
    try {
      const jsonStart = responseText.indexOf('[');
      const jsonEnd = responseText.lastIndexOf(']') + 1;
      trends = JSON.parse(responseText.slice(jsonStart, jsonEnd));
    } catch (e) {
      console.warn("Gemini JSON parse failed, using fallback trends.");
      trends = [
        { title: "Quantum Computing breakthroughs in 2026", category: "Tech" },
        { title: "India's new digital commerce regulations", category: "Business" }
      ];
    }

    for (const trend of trends) {
      // Logic to check, generate, and publish
      const trendsRef = db.collection("trends");
      const existingTrend = await trendsRef.where("title", "==", trend.title).get();
      
      if (existingTrend.empty) {
        await trendsRef.add({
          ...trend,
          status: "pending",
          fetchedAt: new Date().toISOString()
        });
        
        // Trigger Blog Generation for this trend
        console.log("Processing new trend:", trend.title);
        // [Integration logic for keywords -> blog -> image -> odoo would go here]
        
        // Mocking a successful blog generation for the list
        await db.collection("blogs").add({
          title: trend.title,
          content: "Full SEO content generated by AI...",
          status: "draft",
          createdAt: new Date().toISOString(),
          keywords: ["SEO", trend.category, "India"],
          trendId: trend.title
        });
      }
    }

    await configRef.update({ lastRun: new Date().toISOString() });
    console.log("Pipeline completed.");
  } catch (error) {
    console.error("Pipeline failed:", error);
  }
}

// Cron Job: Every 30 minutes
cron.schedule("*/30 * * * *", () => {
  runAutomationPipeline();
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.get("/api/health", (req, res) => res.json({ status: "ok" }));

  app.post("/api/generate-manual", async (req, res) => {
    console.log("Manual trigger received");
    await runAutomationPipeline();
    res.json({ success: true });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", async () => {
    console.log(`Server running on http://localhost:${PORT}`);
    
    // Initialize settings if missing
    const configRef = db.collection("settings").doc("config");
    const doc = await configRef.get();
    if (!doc.exists) {
      await configRef.set({
        autoMode: false,
        lastRun: null,
        odooConfig: {
          url: "",
          db: "",
          username: "",
          password: "",
          apiKey: ""
        }
      });
    }
  });
}

startServer();
